### ISSUE TITLE
Ideas for Democracy.gov.sg

### ISSUE THREAD

**Issue by lewweiming** [opengovsg/askgovsg#1432]
Hi there,

I'd like to implement a democratic framework for Singapore using the domain democracy.gov.sg. The framework will help to promote a true democracy in Singapore.

How do I go about doing so? Someone will have to build it.

This is in line with the Singapore pledge "To Build a Democratic Society, Based on Justice and Equality".

**Comment by LoneRifle** [comment]
Thanks for getting in touch! You may wish to approach [REACH](https://www.reach.gov.sg) with your idea, since they handle  citizen engagement for the Government, and will be better placed to hear you out. AskGov's current product direction is to help members of the public find answers to specific and routine matters, such as Covid protocols and licensing in the energy market.

Hope this helps!
